/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlumberNairobiRouteImport } from './routes/plumber-nairobi'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as EmergencyPlumbingNairobiRouteImport } from './routes/emergency-plumbing-nairobi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PlumberNairobiRoute = PlumberNairobiRouteImport.update({
  id: '/plumber-nairobi',
  path: '/plumber-nairobi',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyPlumbingNairobiRoute =
  EmergencyPlumbingNairobiRouteImport.update({
    id: '/emergency-plumbing-nairobi',
    path: '/emergency-plumbing-nairobi',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing-nairobi': typeof EmergencyPlumbingNairobiRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/plumber-nairobi': typeof PlumberNairobiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing-nairobi': typeof EmergencyPlumbingNairobiRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/plumber-nairobi': typeof PlumberNairobiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-plumbing-nairobi': typeof EmergencyPlumbingNairobiRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/plumber-nairobi': typeof PlumberNairobiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-plumbing-nairobi'
    | '/get-a-quote'
    | '/plumber-nairobi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-plumbing-nairobi'
    | '/get-a-quote'
    | '/plumber-nairobi'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-plumbing-nairobi'
    | '/get-a-quote'
    | '/plumber-nairobi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmergencyPlumbingNairobiRoute: typeof EmergencyPlumbingNairobiRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  PlumberNairobiRoute: typeof PlumberNairobiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plumber-nairobi': {
      id: '/plumber-nairobi'
      path: '/plumber-nairobi'
      fullPath: '/plumber-nairobi'
      preLoaderRoute: typeof PlumberNairobiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-plumbing-nairobi': {
      id: '/emergency-plumbing-nairobi'
      path: '/emergency-plumbing-nairobi'
      fullPath: '/emergency-plumbing-nairobi'
      preLoaderRoute: typeof EmergencyPlumbingNairobiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmergencyPlumbingNairobiRoute: EmergencyPlumbingNairobiRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  PlumberNairobiRoute: PlumberNairobiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
